@props(['name' => 'wilaya', 'selected' => null])

<select name="{{ $name }}" id="{{ $name }}" {{ $attributes->merge(['class' => 'form-select border-gray-300 rounded-md shadow-sm']) }}>
    <option value="">-- اختر الولاية --</option>
    @foreach ([
        ['nb' => '01', 'ar' => 'أدرار',       'fr' => 'Adrar'],
        ['nb' => '02', 'ar' => 'الشلف',       'fr' => 'Chlef'],
        ['nb' => '03', 'ar' => 'الأغواط',     'fr' => 'Laghouat'],
        ['nb' => '04', 'ar' => 'أم البواقي',  'fr' => 'Oum El Bouaghi'],
        ['nb' => '05', 'ar' => 'باتنة',       'fr' => 'Batna'],
        ['nb' => '06', 'ar' => 'بجاية',       'fr' => 'Béjaïa'],
        ['nb' => '07', 'ar' => 'بسكرة',       'fr' => 'Biskra'],
        ['nb' => '08', 'ar' => 'بشار',        'fr' => 'Béchar'],
        ['nb' => '09', 'ar' => 'البليدة',     'fr' => 'Blida'],
        ['nb' => '10', 'ar' => 'البويرة',     'fr' => 'Bouira'],
        ['nb' => '11', 'ar' => 'تمنراست',     'fr' => 'Tamanrasset'],
        ['nb' => '12', 'ar' => 'تبسة',        'fr' => 'Tébessa'],
        ['nb' => '13', 'ar' => 'تلمسان',      'fr' => 'Tlemcen'],
        ['nb' => '14', 'ar' => 'تيارت',       'fr' => 'Tiaret'],
        ['nb' => '15', 'ar' => 'تيزي وزو',    'fr' => 'Tizi Ouzou'],
        ['nb' => '16', 'ar' => 'الجزائر',     'fr' => 'Alger'],
        ['nb' => '17', 'ar' => 'الجلفة',      'fr' => 'Djelfa'],
        ['nb' => '18', 'ar' => 'جيجل',        'fr' => 'Jijel'],
        ['nb' => '19', 'ar' => 'سطيف',        'fr' => 'Sétif'],
        ['nb' => '20', 'ar' => 'سعيدة',       'fr' => 'Saïda'],
        ['nb' => '21', 'ar' => 'سكيكدة',      'fr' => 'Skikda'],
        ['nb' => '22', 'ar' => 'سيدي بلعباس', 'fr' => 'Sidi Bel Abbès'],
        ['nb' => '23', 'ar' => 'عنابة',       'fr' => 'Annaba'],
        ['nb' => '24', 'ar' => 'قالمة',       'fr' => 'Guelma'],
        ['nb' => '25', 'ar' => 'قسنطينة',     'fr' => 'Constantine'],
        ['nb' => '26', 'ar' => 'المدية',      'fr' => 'Médéa'],
        ['nb' => '27', 'ar' => 'مستغانم',     'fr' => 'Mostaganem'],
        ['nb' => '28', 'ar' => 'المسيلة',     'fr' => 'M’sila'],
        ['nb' => '29', 'ar' => 'معسكر',       'fr' => 'Mascara'],
        ['nb' => '30', 'ar' => 'ورقلة',       'fr' => 'Ouargla'],
        ['nb' => '31', 'ar' => 'وهران',       'fr' => 'Oran'],
        ['nb' => '32', 'ar' => 'البيض',       'fr' => 'El Bayadh'],
        ['nb' => '33', 'ar' => 'إليزي',       'fr' => 'Illizi'],
        ['nb' => '34', 'ar' => 'برج بوعريريج','fr' => 'Bordj Bou Arreridj'],
        ['nb' => '35', 'ar' => 'بومرداس',     'fr' => 'Boumerdès'],
        ['nb' => '36', 'ar' => 'الطارف',      'fr' => 'El Tarf'],
        ['nb' => '37', 'ar' => 'تندوف',       'fr' => 'Tindouf'],
        ['nb' => '38', 'ar' => 'تيسمسيلت',    'fr' => 'Tissemsilt'],
        ['nb' => '39', 'ar' => 'الوادي',      'fr' => 'El Oued'],
        ['nb' => '40', 'ar' => 'خنشلة',       'fr' => 'Khenchela'],
        ['nb' => '41', 'ar' => 'سوق أهراس',   'fr' => 'Souk Ahras'],
        ['nb' => '42', 'ar' => 'تيبازة',      'fr' => 'Tipaza'],
        ['nb' => '43', 'ar' => 'ميلة',        'fr' => 'Mila'],
        ['nb' => '44', 'ar' => 'عين الدفلى',  'fr' => 'Aïn Defla'],
        ['nb' => '45', 'ar' => 'النعامة',     'fr' => 'Naâma'],
        ['nb' => '46', 'ar' => 'عين تموشنت',  'fr' => 'Aïn Témouchent'],
        ['nb' => '47', 'ar' => 'غرداية',      'fr' => 'Ghardaïa'],
        ['nb' => '48', 'ar' => 'غليزان',      'fr' => 'Relizane'],
        ['nb' => '49', 'ar' => 'تميمون',      'fr' => 'Timimoun'],
        ['nb' => '50', 'ar' => 'برج باجي مختار','fr' => 'Bordj Badji Mokhtar'],
        ['nb' => '51', 'ar' => 'أولاد جلال',  'fr' => 'Ouled Djellal'],
        ['nb' => '52', 'ar' => 'بني عباس',    'fr' => 'Béni Abbès'],
        ['nb' => '53', 'ar' => 'إن صالح',     'fr' => 'In Salah'],
        ['nb' => '54', 'ar' => 'إن قزام',     'fr' => 'In Guezzam'],
        ['nb' => '55', 'ar' => 'تقرت',        'fr' => 'Touggourt'],
        ['nb' => '56', 'ar' => 'جانت',        'fr' => 'Djanet'],
        ['nb' => '57', 'ar' => 'المغير',      'fr' => 'El M’ghair'],
        ['nb' => '58', 'ar' => 'المنيعة',     'fr' => 'El Meniaa'],
    ] as $wilaya)
        <option value="{{ $wilaya['nb'] }}" @selected($selected == $wilaya['nb'])>
            {{ $wilaya['nb'] }} - {{ $wilaya['ar'] }} ({{ $wilaya['fr'] }})
        </option>
    @endforeach
</select>
